version: "3"
services:
  nba-fantasy-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_DB=nba_fantasy
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
   data:
