spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nba_fantasy
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${NBA_FANTASY_EMAIL}
    password: ${NBA_FANTASY_EMAIL_PASS}
    properties:
      mail:
        smtp:
          starttls.required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  jackson:
    default-property-inclusion=always, non_null, non_absent, non_default, non_empty

web:
  driver:
    path: ${WEB_DRIVER_PATH}
server:
  error:
    path: /error
